const hikmetData = {
  hikmetliSozler: [
    "Zaman, sabredenler için hayırlı sırlar taşır.",
    "Her gecenin bir sabahı, her zorluğun bir kolaylığı vardır.",
    "Kalp huzuru, dünya hazinelerinden daha değerlidir.",
    "İnsan, niyeti kadar güzeldir.",
    "Sabır, kurtuluşun anahtarıdır.",
    "Hikmet, müminin yitik malıdır; nerede bulursa alır.",
    "En büyük zafer, insanın kendini tanımasıdır.",
    "Rüyalar, kalbin penceresidir.",
    "Her rüya, bir hikmet taşır.",
    "Gece, sırların bekçisidir.",
  ],
  hadisler: [
    "Zalimlere yardım etmeyin. - Tirmizi",
    "Rüya üç çeşittir: Allah'tan bir müjde olan rüya, şeytandan olan rüya ve kişinin kendi kendine konuştuğu rüya. - Buhari",
    "Güzel rüya, Allah'tandır. - Müslim",
    "Rüyasında hoşlanmadığı bir şey gören sol tarafına üç defa üflesin. - Buhari",
    "Müminin rüyası, nübüvvetin kırk altı cüzünden bir cüzdür. - Buhari",
    "Kim beni rüyasında görürse gerçekten görmüştür. - Buhari",
    "Sadık rüya vahyin bir parçasıdır. - Tirmizi",
    "En doğru rüya, seher vaktinde görülen rüyadır. - İbn Mace",
    "Rüya gören, onu ancak sevdiği kimseye anlatsın. - Müslim",
    "Gece namazı kılan kimsenin gündüzü nurlu olur. - Taberani",
  ],
  ayetler: [
    "Kalpler ancak Allah'ı anmakla huzur bulur. (Ra'd 28)",
    "Şüphesiz zorlukla beraber bir kolaylık vardır. (İnşirah 6)",
    "Allah sabredenlerle beraberdir. (Bakara 153)",
    "Biz insana şah damarından daha yakınız. (Kaf 16)",
    "Sizin hayır bildiklerinizde şer, şer bildiklerinizde hayır olabilir. (Bakara 216)",
    "Rabbiniz duanızı işitir. (İsra 25)",
    "Her nefis ölümü tadacaktır. (Ankebut 57)",
    "Göklerin ve yerin anahtarları O'nundur. (Şura 12)",
    "O, kullarının üstünde mutlak hakimiyet sahibidir. (En'am 18)",
    "Kim Allah'a güvenirse, O ona yeter. (Talak 3)",
  ],
  tefekkur: [
    "Rüyalarınızda sizi en çok etkileyen duygu nedir? Bu duygunun günlük hayatınızdaki yansımalarını düşünün...",
    "Gördüğünüz rüyalar size hangi mesajları fısıldıyor? Kalbinizin sesini dinleyin...",
    "Her rüya bir öğreti midir, yoksa bazıları sadece zihnin dinlenmesi mi? Bugün gördüğünüz rüyayı bu açıdan değerlendirin...",
    "Rüyalarınızda tekrar eden semboller var mı? Bu sembollerin hayatınızdaki karşılıklarını düşünün...",
    "Rüyalar gerçekten de hakikatin gölgesi midir? Kendi tecrübelerinizden yola çıkarak derinlemesine düşünün...",
    "Gece gördüğünüz rüyalar, gündüz yaptığınız işleri nasıl etkiliyor? Bu etkileşimi gözlemleyin...",
    "Rüyalarınızda size rehberlik eden bir ses veya işaret var mı? Bu rehberliğin mahiyeti üzerine tefekkür edin...",
  ],
};

export default hikmetData;
